### ISSUE TITLE
matrix size

### ISSUE THREAD

**Issue by Wu-Wenxuan** [socathie/circomlib-matrix#2]
Hi.

Thank you for the implementation. Have you tested the maximum size of the matrix circom can support? I tried to multiply two matrices of size 128*128 each and got an error "(node:31079) UnhandledPromiseRejectionWarning: Error: Too many values for input signal a". 

This is only 2M constraints and I think circom should support. Do you have any idea/suggestions?

**Comment by socathie** [comment]
Hi @ww6726 this error doesn't seem to be related to size allowed. Can you check the json that contains your input signal and make sure `a` has the correct number of values? This error is suggesting that you have more values than the dimensions of `a` in your input signal file.

**Comment by Wu-Wenxuan** [comment]
Hi @socathie. I've check the size in my json file and yes the numbers are correct. I wrote a script that can generate various size of matrices for circom and other smaller sizes works with no problem. Can you explain what input signal file is; is that the input.json?

**Comment by socathie** [comment]
In this case, this is likely an issue with circom itself.
